services:
  daemon:
    image: rea1shane/lego-docker-helper
    container_name: demo-lego-docker-helper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./test.sh:/test.sh

  nginx:
    image: nginx
    labels:
      - helper.docker.lego.discovery.domain=example.com

  traefik:
    image: traefik
    labels:
      - helper.docker.lego.discovery.domain=foo.bar
